"""Add student schema and temporary import previews

Revision ID: 0002_import_preview
Revises: 0001_departments
Create Date: 2026-09-09 07:45:33.261433
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = '0002_import_preview'
down_revision: Union[str, Sequence[str], None] = '0001_departments'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('academic_periods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=80), nullable=False),
    sa.Column('period_key', sa.String(length=80), nullable=False),
    sa.CheckConstraint('length(trim(label)) > 0 AND length(period_key) > 0', name='ck_period_label'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('period_key')
    )
    op.create_table('import_batches',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('profile', sa.String(length=64), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('scope', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('proposal', sa.JSON(none_as_null=True), nullable=True),
    sa.CheckConstraint("scope IN ('PADRON_COMPLETO','SUBCONJUNTO')", name='ck_import_scope'),
    sa.CheckConstraint("status IN ('PREVIEW','EXPIRED')", name='ck_import_status'),
    sa.CheckConstraint('expires_at > created_at', name='ck_import_expiry'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_batches_expires_at'), 'import_batches', ['expires_at'], unique=False)
    op.create_table('import_rows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.String(length=36), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=24), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.CheckConstraint("category IN ('NUEVO','SIN_CAMBIOS','ACTUALIZACION','REQUIERE_REVISION')", name='ck_import_category'),
    sa.ForeignKeyConstraint(['batch_id'], ['import_batches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batch_id', 'row_number', name='uq_import_row')
    )
    op.create_index(op.f('ix_import_rows_batch_id'), 'import_rows', ['batch_id'], unique=False)
    op.create_table('institution',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=240), nullable=False),
    sa.Column('active_academic_period_id', sa.Integer(), nullable=True),
    sa.CheckConstraint('id = 1', name='ck_institution_singleton'),
    sa.CheckConstraint('length(trim(name)) > 0', name='ck_institution_name'),
    sa.ForeignKeyConstraint(['active_academic_period_id'], ['academic_periods.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=160), nullable=False),
    sa.Column('middle_name', sa.String(length=160), nullable=True),
    sa.Column('last_name', sa.String(length=160), nullable=False),
    sa.Column('second_last_name', sa.String(length=160), nullable=True),
    sa.Column('document', sa.String(length=80), nullable=True),
    sa.Column('document_type', sa.String(length=80), nullable=True),
    sa.Column('active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('source_batch_id', sa.String(length=36), nullable=True),
    sa.Column('source_baseline', sa.JSON(none_as_null=True), nullable=True),
    sa.CheckConstraint('active IN (0,1)', name='ck_student_active'),
    sa.CheckConstraint('length(trim(first_name)) > 0 AND length(trim(last_name)) > 0', name='ck_student_names'),
    sa.ForeignKeyConstraint(['source_batch_id'], ['import_batches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_students_document'), 'students', ['document'], unique=False)
    op.create_table('student_academic_placements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('academic_period_id', sa.Integer(), nullable=False),
    sa.Column('course', sa.String(length=160), nullable=False),
    sa.Column('parallel', sa.String(length=40), nullable=False),
    sa.Column('recorded_from', sa.DateTime(), nullable=False),
    sa.Column('recorded_to', sa.DateTime(), nullable=True),
    sa.Column('source_batch_id', sa.String(length=36), nullable=True),
    sa.CheckConstraint('length(trim(course)) > 0 AND length(trim(parallel)) > 0', name='ck_placement_fields'),
    sa.CheckConstraint('recorded_to IS NULL OR recorded_to >= recorded_from', name='ck_placement_dates'),
    sa.ForeignKeyConstraint(['academic_period_id'], ['academic_periods.id'], ),
    sa.ForeignKeyConstraint(['source_batch_id'], ['import_batches.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_placement_open', 'student_academic_placements', ['student_id', 'academic_period_id'], unique=True, sqlite_where=sa.text('recorded_to IS NULL'))
    op.create_table('student_contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=24), nullable=False),
    sa.Column('relationship', sa.String(length=80), nullable=True),
    sa.Column('first_name', sa.String(length=160), nullable=True),
    sa.Column('middle_name', sa.String(length=160), nullable=True),
    sa.Column('last_name', sa.String(length=160), nullable=True),
    sa.Column('second_last_name', sa.String(length=160), nullable=True),
    sa.Column('home_phone', sa.String(length=80), nullable=True),
    sa.Column('mobile_phone', sa.String(length=80), nullable=True),
    sa.Column('work_phone', sa.String(length=80), nullable=True),
    sa.Column('active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('source_batch_id', sa.String(length=36), nullable=True),
    sa.Column('source_baseline', sa.JSON(none_as_null=True), nullable=True),
    sa.CheckConstraint("type IN ('REPRESENTANTE_LEGAL','PADRE','MADRE','EMERGENCIA')", name='ck_contact_type'),
    sa.CheckConstraint('active IN (0,1)', name='ck_contact_active'),
    sa.ForeignKeyConstraint(['source_batch_id'], ['import_batches.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_contact_single_role', 'student_contacts', ['student_id', 'type'], unique=True, sqlite_where=sa.text("active = 1 AND type != 'EMERGENCIA'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_contact_single_role', table_name='student_contacts', sqlite_where=sa.text("active = 1 AND type != 'EMERGENCIA'"))
    op.drop_table('student_contacts')
    op.drop_index('uq_placement_open', table_name='student_academic_placements', sqlite_where=sa.text('recorded_to IS NULL'))
    op.drop_table('student_academic_placements')
    op.drop_index(op.f('ix_students_document'), table_name='students')
    op.drop_table('students')
    op.drop_table('institution')
    op.drop_index(op.f('ix_import_rows_batch_id'), table_name='import_rows')
    op.drop_table('import_rows')
    op.drop_index(op.f('ix_import_batches_expires_at'), table_name='import_batches')
    op.drop_table('import_batches')
    op.drop_table('academic_periods')
    # ### end Alembic commands ###
